new tests for project
mehalyna/Wr-52.TAQC-Python-TestProject pull request #19
Opened 2023-05-08 12:06 UTC by MuyanjaKevin

These are some of the changes i have made and some more tests i made

- testing for login
- testing for registeration with correct credentials
- testing registeration with incorrect credentials
- testing that login form appears after join events express button is clicked
- testing redirection when different links are clicked e.g about,contact,terms ,etc

2023-05-08 12:46 UTC, mehalyna commented on config.py
> +
don't push any credentials in github repo

2023-05-08 12:48 UTC, mehalyna commented on config.py
> +JOIN_EVENT_URL = 'https://eventsexpress-test.azurewebsites.net/home/events/8d58c4dc-0d43-44bd-4e71-08da439568bd'
we don't need the list of urls here

2023-05-08 13:08 UTC, mehalyna commented on src/pages/LandingPage.py
> +    CONTACT_US_BUTTON_CSS = '#root > div > footer > div.links-to-pages > a:nth-child(4)'
Try to shorten selectors

2023-05-08 13:09 UTC, mehalyna commented on src/pages/LandingPage.py
> +    EXPLORE_MORE_EVENTS_BTN_CSS = '#root > div > div > article.events-article > div.row > div.col-md-2 > a'
eg.
.events-article>div>div:last-of-type>a

2023-05-08 13:11 UTC, mehalyna commented on src/pages/LandingPage.py
> +        return self.find_element_by_css(self.CONTACT_US_BUTTON_CSS)
suppose we have to define FooterPartPage and define all these methods here.
Consequently we'll use it throughout all pages

2023-05-08 13:12 UTC, mehalyna commented on src/pages/LandingPageForAuthorizedUser.py
> +
delete these rows, pls

2023-05-08 13:15 UTC, mehalyna commented on tests/conftest.py
> +    app.modal.login(config.USER_EMAIL, config.USER_PASSWORD)
create one more method for the authorization of ordinary users. Don't change this one

2023-05-08 13:16 UTC, mehalyna commented on tests/testScripts/test_landing.py
> +
don't change the functionality and purpose of this method. Create one more instead

2023-05-08 13:18 UTC, mehalyna commented on tests/testScripts/test_landing.py
> +    app.modal.registration(config.INVALID_REGISTER_EMAIL, config.INVALID_REGISTER_PASSWORD)
in config you may use only constants with valid data. All other data are test data. We'll use them as from files or define them just here, in TC

2023-05-08 13:21 UTC, mehalyna commented on tests/testScripts/test_landing.py
> +    time.sleep(10)
we cannot use urls for assertions. We have to verify if we were redirected to the correct page. So try to handle any text or label on it

2023-05-10 10:41 UTC, Thoughtseize1 commented on config.py
> +INVALID_REGISTER_PASSWORD = '123'
remove it from config.py and push invalid data in TC.

2023-05-10 17:58 UTC, servettonga requested changes
Your base is old. Merge changes to your branch first.

2023-05-10 18:00 UTC, servettonga commented on src/pages/FooterPage.py
Work on Footer.py instead.

2023-05-11 20:00 UTC, Thoughtseize1 requested changes

2023-05-11 20:00 UTC, Thoughtseize1 commented on src/pages/PrivacyPage.py
> +        return self.find_element_by_css(self.PRIVACY_HEADING_CSS).text
Here you also can create a variables with object and text

2023-05-12 22:06 UTC, Thoughtseize1 commented on src/pages/PrivacyPage.py
> +    """
Make docstrin in one line

2023-05-12 22:06 UTC, Thoughtseize1 commented on src/pages/PrivacyPage.py
> +        return self.find_element_by_css(self.PRIVACY_HEADING_CSS).text
You also can make var for it

2023-05-12 22:09 UTC, Thoughtseize1 commented on tests/conftest.py
> +    """
Shorter docstring would be better - https://www.datacamp.com/tutorial/docstrings-python

2023-05-12 22:10 UTC, Thoughtseize1 commented on tests/testScripts/test_landing.py
> +    assert expected_result == app.privacy.get_Privacy_page_heading()
Looks good but would be better if you write the last 2 string into one. 
`assert app.landing_authorized_user.drop_down_menu`

2023-05-12 22:11 UTC, Thoughtseize1 requested changes
Make changes )

2023-05-13 16:13 UTC, closed without merging